If risk complete merge
wolfinj/Extra-tasks pull request #1
Opened 2022-08-24 17:43 UTC by wolfinj

2022-08-24 18:43 UTC, EdgarsSalmins commented on If-Risk.UnitTests/InsuranceCompanyTest.cs
> +        var risks = new List<Risk>
iznest klases līmenī un nosaukt par _availableRisks?

2022-08-24 18:43 UTC, EdgarsSalmins commented on If-Risk.UnitTests/InsuranceCompanyTest.cs
> +        _megaSafe.AvailableRisks.Count.Should().Be(5);
magic number.. :) labāk būtu ja tie riski būtu klases līmenī.. tad šeit varētu pārbaudīt _availableRisks.Count

2022-08-24 18:44 UTC, EdgarsSalmins commented on If-Risk.UnitTests/InsuranceCompanyTest.cs
> +    public void InsuranceCompany_CreateNewCompany_CheckAvailableRisks()
InsuranceCompany_CreateCompany_Company_Has_5_Risks

2022-08-24 18:46 UTC, EdgarsSalmins commented on If-Risk.UnitTests/InsuranceCompanyTest.cs
> +    public void InsuranceCompany_SellPolicy_CheckPolicyCount()
...SellPolicy_PolicyAddedToPoliciesList

2022-08-24 18:46 UTC, EdgarsSalmins commented on If-Risk.UnitTests/InsuranceCompanyTest.cs
> +    public void InsuranceCompany_SellPolicyInPast_GetException()
...ThrowsArgumentException

2022-08-24 18:47 UTC, EdgarsSalmins commented on If-Risk.UnitTests/InsuranceCompanyTest.cs
> +    public void InsuranceCompany_SellPolicyWithOverlappingDates_GetException()
...ThrowsArgumentException

2022-08-24 18:49 UTC, EdgarsSalmins commented on If-Risk.UnitTests/InsuranceCompanyTest.cs
> +    public void InsuranceCompany_SellPolicyWithUnavailableRisks_GetException()
tas pats kas augstāk.. GetException ir pāraķ Generic. :)

2022-08-24 18:52 UTC, EdgarsSalmins commented on If-Risk.UnitTests/InsuranceCompanyTest.cs
> +    public void InsuranceCompany_AddRiskToActivePolicy_GetRiskCountAndCorrectPremium()
Correct PRemium arī nebūs labi... 
AddRiskToActivePolicy_RiskCountIncreasedPremiumRecalculated?
vai kkā precīzāk jāizdomā nosaukt tas ko Tu pārbaudi un ko sagaidi. :)

2022-08-24 19:53 UTC, wolfinj commented on If-Risk.UnitTests/InsuranceCompanyTest.cs
> +        var risks = new List<Risk>
Man tā bija, un tad Reshapers ieteica pārtaisīt par lokālo...

2022-08-25 05:36 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +        if (validFrom < DateTime.Now) throw new ArgumentException("Policy starting date can not be in past!");
no 44 līdz 56 rindai izskatās pēc kkāda validātora? ko varētu iznest vai nu metodē vai nu vispār citā klasē?

2022-08-25 05:36 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +        Policies = new List<Policy>();
labāk būtu padot no ārpuses. :) 
arī testēt uzreiz ir vieglāk. :)

2022-08-25 05:37 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +        if (!_availableRisks.Contains(risk)) throw new ArgumentException($"{risk.Name} is not available!");
Riska validēšana vaŗetu būt iznesama kkur ārpusē.

2022-08-25 05:38 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +        if (!_availableRisks.Contains(risk)) throw new ArgumentException($"{risk.Name} is not available!");
RiskExistsException?

2022-08-25 05:38 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +            throw new ArgumentException($"Insurance \"{nameOfInsuredObject}\" do not exist!");
InsuredObjectDoesNotExistsException?

2022-08-25 05:38 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +            throw new ArgumentException($"Policy expired at {selectedInsuranceObject.ValidTill}");
PolicyExpiredException?

2022-08-25 05:39 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +            throw new ArgumentException("One or more risks are not available!");
RiskNotAvailableException?

2022-08-25 05:39 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +            throw new ArgumentException("Policy with the same name cant overlap period!");
DuplicatePolicyException? vai PolicyPeriodOverlapException?

2022-08-25 05:40 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +            throw new ArgumentException($"There is no policy with name \"{nameOfInsuredObject}\"!");
PolicyNotFoundException?

2022-08-25 05:41 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +            x.ValidTill >= effectiveDate) ?? throw new ArgumentException("There is no walid Policy at this time!");
InvalidPolicyException?

2022-08-25 05:41 UTC, EdgarsSalmins commented on If-Risk/Policy.cs
> +    private void CalculatePremium()
Polisei nebūtu jāprot aprēķināt PRemium. :)

2022-08-25 05:43 UTC, EdgarsSalmins commented on If-Risk/Policy.cs
> +    public DateTime ValidTill => _validTill;
kapēc ValidFrom ir ar vienkāršu getteri bet valid Till ir kkas caur privātu mainīgo? 
kapēc atšķiras?

2022-08-25 05:44 UTC, EdgarsSalmins commented on If-Risk/Policy.cs
> +        Premium += risk.YearlyPrice / 12 * (_validTill.Month - validFrom.Month);
atkārtojas loģika ar CalculatePremium metodi.

2022-08-25 05:45 UTC, EdgarsSalmins commented on If-Risk/Policy.cs
> +        _insuredRisks = (List<Risk>?)insuredRisks;
kapēc jākāsto?

2022-08-25 05:46 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +            x.ValidTill >= effectiveDate) ?? throw new ArgumentException("There is no walid Policy at this time!");
+ drukas kļūda => walid

2022-08-25 05:47 UTC, EdgarsSalmins commented on If-Risk.UnitTests/RiskTests.cs
> +        Risk test = new Risk("Test", 1);
Šī būs act daļa.

2022-08-25 05:47 UTC, EdgarsSalmins commented on If-Risk.UnitTests/RiskTests.cs
> +        var testName = test.Name == "Test";
Šo var mest ārā.. nekāda darbība te īsti nenotiek.

2022-08-25 05:48 UTC, EdgarsSalmins commented on If-Risk.UnitTests/RiskTests.cs
> +        testName.Should().BeTrue();
un šis tikai parbauda 14 rindā ka tā tas ir bet 17 rinda jau to pašu izdara. 
doesn't make sense.

2022-08-25 05:50 UTC, EdgarsSalmins commented on If-Risk.UnitTests/PolicyTests.cs
> +public class PolicyTests
ja liki komentārus risk testos /Arrange //act //assert tad liec visur.. vai neliec nekur.

2022-08-25 05:54 UTC, EdgarsSalmins commented on If-Risk/InsuranceCompany.cs
> +        if (validFrom < DateTime.Now) throw new ArgumentException("Policy starting date can not be in past!");
Tev daudz kur nepieciešama polises meklēšana... varbūt ir saprātīgi to daļu iznest ārā lai loģika neatkārtojas?

2022-08-25 05:57 UTC, EdgarsSalmins requested changes
Prasās uzlabojumi.. 
Testu metodem nosaukumi ir pārāk vispārīgi.. pēc nosaukuma ja tests neiziet nebūs skaidrs kas salūza.. piemēram RiskAdded_PremiumRecalculated... no nosaukuma būs grūti saprast kas nenostŗadāja.. 
un saprast vajadzēs debagot un iedziļināties.. 
nevienu paštaisītu exception nemanīju.. tas bija arī pie paša uzdevuma nosacījumos.. 
pie koda lasāmības jāpiedomā... pagaidām sanāk jāiedziļinās lai saprastu kas tur notiek.. nevar vienkārši izlasīt un uzreiz skaidrs kas notiek vismaz tādā augstākā līmeni.

2022-08-25 08:57 UTC, wolfinj commented on If-Risk/InsuranceCompany.cs
> +        Policies = new List<Policy>();
ko tu domaa padot no aarpuses? name un _availableRisks jau nāk no ārpuses, un Policies tikai tiek inicializēts. Vai tu domā uztaisīt konstruktoru kuram var uztaisīt jaunu kompāniju jau ar eksistējoš''am polisēm?'

2022-08-25 09:14 UTC, wolfinj commented on If-Risk/Policy.cs
> +        Premium += risk.YearlyPrice / 12 * (_validTill.Month - validFrom.Month);
CalculatePremium aprēķina pēc listes. ad risk after pieskaita klāt konkrēto cenu jau aprēķinātai. Bet es sapratu ka šis vis ir jāpārdomā lai polisei nebūtu jārēķina premiums

2022-08-25 09:15 UTC, wolfinj commented on If-Risk/Policy.cs
> +        _insuredRisks = (List<Risk>?)insuredRisks;
Raider o_O :)

2022-08-25 09:26 UTC, wolfinj commented on If-Risk.UnitTests/PolicyTests.cs
> +public class PolicyTests
tas bija pats pats sākums kad gāju līdzi tutoriālim :)

2022-08-26 04:26 UTC, EdgarsSalmins commented on If-Risk.UnitTests/InsuranceCompanyTest.cs
> +    public void InsuranceCompany_SellPolicyInPast_ThrowsInvalidPolicyStartingTimeException()
Perfekts testa nosaukums. :)

2022-08-26 04:32 UTC, EdgarsSalmins commented on If-Risk/IInsuranceCompany.cs
> +    IPolicy SellPolicy(string nameOfInsuredObject, DateTime validFrom, short validMonths, List<Risk> selectedRisks);
kapēc pamainīji doto?

2022-08-26 04:35 UTC, EdgarsSalmins reviewed
If Risk projektam ir jābūt nevis console app bet class library.

2022-08-26 04:37 UTC, EdgarsSalmins commented
lieku visualo studiju lai pārbaudītu testu coverage...
tikko tas būs tā pabeigšu ar šo. :) pagaidām on hold. :)

2022-08-26 04:42 UTC, wolfinj commented on If-Risk/IInsuranceCompany.cs
> +    IPolicy SellPolicy(string nameOfInsuredObject, DateTime validFrom, short validMonths, List<Risk> selectedRisks);
Laikam netīšām kad noņēmu casting

2022-08-26 14:48 UTC, EdgarsSalmins approved these changes

2022-08-26 14:49 UTC, EdgarsSalmins commented
Console app lieta jānoņem.. un pārējais jau izskatās +/- ok.. :) 
coverage ir uz 80 %.. ;) ir labi.

2022-08-26 17:01 UTC, merged